export const UPDATE_ELEMENTS = 'UPDATE_ELEMENTS';
export const UPDATE_INPUT_ELEMENTS = 'UPDATE_INPUT_ELEMENTS';
export const START_DRAGGING = 'START_DRAGGING';
export const STOP_DRAGGING = 'STOP_DRAGGING';
export const TOGGLE_HOVER = 'TOGGLE_HOVER';