export const UPDATE_ELEMENTS = 'UPDATE_ELEMENTS';
export const UPDATE_INPUT_ELEMENTS = 'UPDATE_INPUT_ELEMENTS';
export const TOGGLE_HOVER = 'TOGGLE_HOVER';
export const SET_NEW_POSITION = 'SET_NEW_POSITION';
export const SET_DRAGGED = 'SET_DRAGGED';